# import tkinter
# up = 'top'
# tt = tkinter.Tk()
# wl = 0
# text = tkinter.Text(tt)
# while(wl < 5):
#     wl = wl + 1
#     lb = tkinter.Listbox(tt)
#     lb.insert(1, " 1 ")
#     lb.insert(2, " 2 ")
#     lb.insert(3, " 3 ")
#     lb.insert(4, " 4 ")
#     lb.insert(5, " 5 ")
#     lb.insert(6, " 6 ")
#     lb.insert(7, " 7 ")
#     lb.insert(8, " 8 ")
#     lb.insert(9, " 9 ")
# lb.pack()
# tt.mainloop()
# import tkinter
# top = tkinter.Tk()
# C = tkinter.Canvas(top, bg="blue", height=250, width=300)
# coord = 100, 100, 24, 21
# arc = C.create_arc(coord, start=0, extent=10, fill="red")
# C.pack()
# top.mainloop()
# import tkinter
# tt = tkinter.Tk()
# b = tkinter.Label(tt, text = "Number 1 -;")
# b.pack(side = "left")
# c = tkinter.Entry(tt, bd = 5)
# c.pack(side = "bottom")
# d = tkinter.Label(tt, text = "Number 2 -;")
# d.pack(side = "right")
# e = tkinter.Entry(tt, bd = 5)
# e.pack(side = "bottom")
# usern = tkinter.Label(tt, text = "Name")
# usern.pack(side = "top")
# user = tkinter.Entry(tt, bd = 7)
# user.pack(side = "top")
# var = tkinter.StringVar()
# f = tkinter.Label(tt, textvariable = var, relief = "raised")
# var.set("Hello")
# f.pack(side = "top")
# tt.mainloop()
# import tkinter
# root = tkinter.Tk()
# var = tkinter.StringVar()
# label = tkinter.Label( root, textvariable=var, relief="raised" )
# var.set("Hey!? How are you doing?")
# label.pack()
# root.mainloop()
import tkinter
top = tkinter.Tk()
# B = tkinter.Button(top, text ="Hello")
c = tkinter.Canvas(top, height = 650, width = 650)
fn = tkinter.PhotoImage(file = "task1.png")
d = c.create_image(655, 600, anchor = "ne", image = fn)
c.pack(side = "bottom")
# B.pack(side = "top")
top.mainloop()