import tkinter as tk
top = tk.Tk()
top.configure(background = "red")
def submit():
    root = tk.Tk() 
    root.configure(background="blue") 
    root.title("CREATED PROFILE!!!")
    b = NameE.get()
    tk.Label(root, text = " ", bg = "blue", fg = "red").grid(row = 0, column = 0)
    tk.Label(root, text = "Your name is  ").grid(row = 1, column = 0)
    tk.Label(root, text = b).grid(row = 1, column = 1)
    tk.Label(root, text = " ", bg = "blue", fg = "blue").grid(row = 2)
    c = EmailE.get()
    tk.Label(root, text = "Your email id is ").grid(row = 3, column = 0)
    tk.Label(root, text = c).grid(row = 3, column = 1)
    tk.Label(root, text = " ", bg = "blue", fg = "blue").grid(row = 4, column = 0)
    tk.Label(root, text = "Your gender is ").grid(row = 5, column = 0)
    if fm.get() == 1:
        tk.Label(root, text = "Male").grid(row = 5, column = 1)
    else:
        tk.Label(root, text = "Female").grid(row = 5, column = 1)
    tk.Label(root, text = " ", bg = "blue", fg = "blue").grid(row = 6, column = 0)
    tk.Label(root, text = "Your country is ").grid(row = 7, column = 0)
    country = tk.Label(root, text = tkvar.get())
    country.grid(row = 7, column = 1)
    tk.Label(root, text = " ", bg = "blue", fg = "blue").grid(row = 8, column = 0)
    tk.Label(root, text= "Your favourite food(s) is/are-;").grid(row = 9, column = 0)
    if CheckVar1.get() == 1:
        tk.Label(root, text= "French Fries, ").grid(row = 10, column = 0)
    if CheckVar2.get() == 1:
        tk.Label(root, text= "Pizza, ").grid(row = 11, column = 0)
    if CheckVar3.get() == 1:
        tk.Label(root, text= "Cake, ").grid(row =12, column = 0)
    if CheckVar4.get() == 1:
        tk.Label(root, text= "Burger, ").grid(row = 13, column = 0)
    tk.Label(root, text= "etc.").grid(row = 14, column = 0)
    return
def quiter():
    exit()
fm = tk.IntVar()
fm.set(0)
Name = tk.Label(top, text="Full Name")
Name.grid(row = 0, column = 0)
NameE = tk.Entry(top, bd = 10, width = 25)
NameE.grid(row = 0, column = 1)
Email = tk.Label(top, text="Email ID")
Email.grid(row = 1, column = 0)
EmailE = tk.Entry(top, bd = 10, width = 30)
EmailE.grid(row = 1, column = 1)
Gend_1 = tk.Label(top, text="Gender")
Gend_1.grid(row = 2, column = 0)
Gender_1 = tk.Radiobutton(top, text = "Male",padx = 20, variable = fm, value = 1)
Gender_1.grid(row = 4, column = 0)
Gender_2 = tk.Radiobutton(top, text = "Female",padx = 20, variable = fm, value = 2)
Gender_2.grid(row = 4, column = 1)
tk.Label(top, text = " ", bg = "red", fg = "red").grid()
count =("Asia", "Africa", "America", "Oceania")
tkvar = tk.StringVar()
tkvar.set('select')
popup = tk.OptionMenu(top, tkvar, *count)
popup.grid(row = 6, column = 0)
tk.Label(top, text = " ", bg = "red", fg = "red").grid()
C = tk.Label(top, text = "Pick your favourite food -;")
C.grid(row = 8, column = 0)
CheckVar1 = tk.IntVar()
CheckVar2 = tk.IntVar()
CheckVar3 = tk.IntVar()
CheckVar4 = tk.IntVar()
C1 = tk.Checkbutton(top, text = "French fries", variable = CheckVar1,  onvalue = 1, offvalue = 0)
C2 = tk.Checkbutton(top, text = "Pizza", variable = CheckVar2, onvalue = 1, offvalue = 0)
C3 = tk.Checkbutton(top, text = "Cake", variable = CheckVar3, onvalue = 1, offvalue = 0)
C4 = tk.Checkbutton(top, text = "Burger", variable = CheckVar4, onvalue = 1, offvalue = 0)
tk.Label(top, text = " ", bg = "red", fg = "red").grid(row = 9)
C1.grid(row = 10, column = 0)
C2.grid(row = 10, column = 1)
tk.Label(top, text = " ", bg = "red", fg = "red").grid(row = 9)
C3.grid(row = 12, column = 0)
C4.grid(row = 12, column = 1)
tk.Label(top, text = " ", bg = "red", fg = "red").grid()
Button = tk.Button(top, text = "SUBMIT", command = submit)
Button.grid(row = 20, column = 0)
Button2 = tk.Button(top, text="EXIT", command = quiter)
Button2.grid(row = 20, column = 1)
top.mainloop()